### ISSUE TITLE
broken css - buttons for ordering/searching + footer bar

### ISSUE THREAD

**Issue by scr4bble** [arcs-/Adminer-Material-Theme#3]
I have created a bug report (at sourceforge) I observed in Adminer when using this theme.
Description together with screenshot is in the link bellow:
https://sourceforge.net/p/adminer/bugs-and-features/598/
used with Adminer version 4.6.1

otherwise thanks a lot for this nice theme :)

**Comment by arcs-** [comment]
Hi, thanks. I pushed a possible fix, it works for me but I don't have your setup so I can't be sure.

**Comment by scr4bble** [comment]
I will try it tomorrow and I'll let you know.
Thanks for such a fast response!

**Comment by scr4bble** [comment]
Works perfectly ! Thanks !

Just the color is changed - I liked the previous one :D but this doesn't matter at all, I can change it in source if I wasn't lazy.

**Comment by arcs-** [comment]
Great!
