### ISSUE TITLE
Import from file hidden

### ISSUE THREAD

**Issue by mazdafunsunn** [arcs-/Adminer-Material-Theme#4]
At import section, file upload section is hidden.
![attels](https://user-images.githubusercontent.com/3892223/37337387-cc7897a6-26bc-11e8-8115-1589210a48c5.png)

**Comment by arcs-** [comment]
Thanks. I have found the issue. Unforgenetlly I don't know how to really fix it, as I would have to remove all the other layout changes to show it. There might be an option for future Adminer updates.

**Comment by LC43** [comment]
Hi, same here. This was a show stopper, had to manually remove the css that hide it.

I don't see other consequences of deleting the  css lines related to the `[...] #form fieldset [...]`.  ( not the ajax ones! )
Edit entries, show structure, search, all seem to work.

![import-adminer-2018-6jul-23__0-56-19](https://user-images.githubusercontent.com/48201/43051528-3cc8e728-8e13-11e8-8b26-61dea1d70ca0.jpg)

**Comment by mmcnl** [comment]
@LC43 Could you share a link to your modified version of adminer.css that fixes this issue? I'm not currently set up to do a rebuild from the source. Thanks so much!

**Update** 
I was able to unminify the css and remove those lines (without needing to rebuild from source).

**Comment by arcs-** [comment]
I've updated the main css file now and it should be fixed
