### ISSUE TITLE
Broken CSS after updating to 4.7.0 (missing columns in table view)

### ISSUE THREAD

**Issue by scr4bble** [arcs-/Adminer-Material-Theme#5]
The theme got a bit broken after the newest update :( 
Could you please look into it when you have time?

The one thing I noticed immediately is missing list of columns in table overview (SHOW STRUCTURE tab). Sometimes it is displayed with scroll bar, sometimes completely missing.

![screenshot from 2018-12-02 17-02-22](https://user-images.githubusercontent.com/6439904/49341928-4891ca80-f654-11e8-8730-cad2a1436a08.png)
![screenshot from 2018-12-02 17-02-40](https://user-images.githubusercontent.com/6439904/49341929-4891ca80-f654-11e8-8b93-593e4d645297.png)

**Comment by scr4bble** [comment]
The screenshots are taken from old version. I have just downloaded the newest version but the issue remains.

**Comment by arcs-** [comment]
should be fixed, thanks for the info. :)
